In [2]:
import numpy as np
from IPython.display import display
import pandas as pd

In [6]:
df = pd.read_csv("hw_mobile.csv")
display(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3333 entries, 0 to 3332
Data columns (total 20 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   State                   3333 non-null   object
 1   Account length          3333 non-null   int64
 2   Area code               3333 non-null   int64
 3   International plan      3333 non-null   object
 4   Voice mail plan         3333 non-null   object
 5   Number vmail messages   3333 non-null   int64
 6   Total day minutes       3323 non-null   float64
 7   Total day calls         3323 non-null   float64
 8   Total day charge        3315 non-null   float64
 9   Total eve minutes       3324 non-null   float64
 10  Total eve calls         3325 non-null   float64
 11  Total eve charge        3333 non-null   float64
 12  Total night minutes     3333 non-null   float64
 13  Total night calls       3332 non-null   float64
 14  Total night charge      3333 non-null   float64
 15  Total intl minutes      3333 non-null   float64
 16  Total intl calls        3333 non-null   int64
 17  Total intl charge       3328 non-null   float64
 18  Customer service calls  3328 non-null   float64
 19  Churn                   3325 non-null   object
dtypes: float64(12), int64(4), object(4)
memory usage: 520.9+ KB

None

In [7]:
print()
display(df.describe().transpose())

,count,mean,std,min,25%,50%,75%,max
Account length,3333.0,101.064806,39.822106,1.00,74.00,101.00,127.000,243.00
Area code,3333.0,437.182418,42.371290,408.00,408.00,415.00,510.000,510.00
Number vmail messages,3333.0,8.099010,13.688365,0.00,0.00,0.00,20.000,51.00
Total day minutes,3323.0,179.787150,54.419625,0.00,143.70,179.40,216.500,350.80
Total day calls,3323.0,100.456214,20.057356,0.00,87.00,101.00,114.000,165.00
Total day charge,3315.0,30.557831,9.255987,0.00,24.42,30.50,36.780,59.64
Total eve minutes,3324.0,201.033935,50.676652,0.00,166.60,201.40,235.325,363.70
Total eve calls,3325.0,100.110677,19.932115,0.00,87.00,100.00,114.000,170.00
Total eve charge,3333.0,17.083540,4.310668,0.00,14.16,17.12,20.000,30.91
Total night minutes,3333.0,200.872037,50.573847,23.20,167.00,201.20,235.300,395.00
Total night calls,3332.0,100.115246,19.566710,33.00,87.00,100.00,113.000,175.00
Total night charge,3333.0,9.039325,2.275873,1.04,7.52,9.05,10.590,17.77
Total intl minutes,3333.0,10.237294,2.791840,0.00,8.50,10.30,12.100,20.00
Total intl calls,3333.0,4.479448,2.461214,0.00,3.00,4.00,6.000,20.00
Total intl charge,3328.0,2.764588,0.754086,0.00,2.30,2.78,3.270,5.40
Customer service calls,3328.0,1.563101,1.315870,0.00,1.00,1.00,2.000,9.00

In [8]:
display(df.head())
print()
display(df.tail())

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110.0,45.07,197.4,99.0,16.78,244.7,91.0,11.01,10.0,3,2.70,1.0,False
1,OH,107,415,No,Yes,26,161.6,123.0,27.47,195.5,103.0,16.62,254.4,103.0,11.45,13.7,3,3.70,1.0,False
2,NJ,137,415,No,No,0,243.4,114.0,41.38,121.2,110.0,10.30,162.6,104.0,7.32,12.2,5,3.29,0.0,False
3,OH,84,408,Yes,No,0,299.4,71.0,50.90,61.9,88.0,5.26,196.9,89.0,8.86,6.6,7,1.78,2.0,False
4,OK,75,415,Yes,No,0,166.7,113.0,28.34,148.3,122.0,12.61,186.9,121.0,8.41,10.1,3,2.73,3.0,False

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
3328,AZ,192,415,No,Yes,36,156.2,77.0,26.55,215.5,126.0,18.32,279.1,83.0,12.56,9.9,6,2.67,2.0,False
3329,WV,68,415,No,No,0,231.1,57.0,39.29,153.4,55.0,13.04,191.3,123.0,8.61,9.6,4,2.59,3.0,False
3330,RI,28,510,No,No,0,180.8,109.0,30.74,288.8,58.0,24.55,191.9,91.0,8.64,14.1,6,3.81,2.0,False
3331,CT,184,510,Yes,No,0,213.8,105.0,36.35,159.6,84.0,13.57,139.2,137.0,6.26,5.0,10,1.35,2.0,False
3332,TN,74,415,No,Yes,25,234.4,113.0,39.85,265.9,82.0,22.60,241.4,77.0,10.86,13.7,4,3.70,0.0,False

In [9]:
display(df['State'])

0       KS
1       OH
2       NJ
3       OH
4       OK
        ..
3328    AZ
3329    WV
3330    RI
3331    CT
3332    TN
Name: State, Length: 3333, dtype: object

In [11]:
display(df[['State','International plan']])

     State International plan
0       KS                 No
1       OH                 No
2       NJ                 No
3       OH                Yes
4       OK                Yes
...    ...                ...
3328    AZ                 No
3329    WV                 No
3330    RI                 No
3331    CT                Yes
3332    TN                 No

[3333 rows x 2 columns]

In [14]:
display('~' * 100, '=========== International plan = Yes and Churn = True', '~' * 100, df[(df['International plan'] == 'Yes') & (df['Churn'] == True)])

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~'

'=========== International plan = Yes and Churn = True'

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~'

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
41,MD,135,408,Yes,Yes,41,173.1,85.0,29.43,203.9,107.0,17.33,122.2,78.0,5.50,14.6,15,3.94,0.0,True
115,ME,36,510,Yes,Yes,42,196.8,89.0,33.46,254.9,122.0,21.67,138.3,126.0,6.22,20.0,6,5.40,0.0,True
144,VT,117,408,Yes,No,0,167.1,86.0,28.41,177.5,87.0,15.09,249.4,132.0,11.22,14.1,7,3.81,2.0,True
198,ME,131,510,Yes,Yes,26,292.9,101.0,49.79,199.7,97.0,16.97,255.3,127.0,11.49,13.8,7,3.73,4.0,True
214,FL,70,510,Yes,No,0,226.7,98.0,38.54,228.1,115.0,19.39,73.2,93.0,3.29,17.6,4,4.75,2.0,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3246,NC,77,408,Yes,Yes,44,103.2,117.0,17.54,236.3,86.0,20.09,203.5,101.0,9.16,11.9,2,3.21,0.0,True
3255,RI,138,510,Yes,No,0,286.2,61.0,48.65,187.2,60.0,15.91,146.2,114.0,6.58,11.0,4,2.97,2.0,True
3291,MI,119,510,Yes,Yes,22,172.1,119.0,29.26,223.6,133.0,19.01,150.0,94.0,6.75,13.9,20,3.75,1.0,True
3304,IL,71,510,Yes,No,0,186.1,114.0,31.64,198.6,140.0,16.88,206.5,80.0,9.29,13.8,5,3.73,4.0,True
3320,GA,122,510,Yes,No,0,140.0,101.0,23.80,196.4,77.0,16.69,120.1,133.0,5.40,9.7,4,2.62,4.0,True

In [18]:
display(df.iloc[df.index % 2 == 0])

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110.0,45.07,197.4,99.0,16.78,244.7,91.0,11.01,10.0,3,2.70,1.0,False
2,NJ,137,415,No,No,0,243.4,114.0,41.38,121.2,110.0,10.30,162.6,104.0,7.32,12.2,5,3.29,0.0,False
4,OK,75,415,Yes,No,0,166.7,113.0,28.34,148.3,122.0,12.61,186.9,121.0,8.41,10.1,3,2.73,3.0,False
6,MA,121,510,No,Yes,24,218.2,88.0,37.09,348.5,108.0,29.62,212.6,118.0,9.57,7.5,7,2.03,3.0,NaN
8,LA,117,408,No,No,0,184.5,97.0,31.37,351.6,80.0,29.89,215.8,90.0,9.71,8.7,4,2.35,1.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3324,WV,159,415,No,No,0,169.8,114.0,28.87,197.7,105.0,16.80,193.7,82.0,8.72,11.6,4,3.13,1.0,False
3326,OH,96,415,No,No,0,106.6,128.0,18.12,284.8,87.0,24.21,178.9,92.0,8.05,14.9,7,4.02,1.0,False
3328,AZ,192,415,No,Yes,36,156.2,77.0,26.55,215.5,126.0,18.32,279.1,83.0,12.56,9.9,6,2.67,2.0,False
3330,RI,28,510,No,No,0,180.8,109.0,30.74,288.8,58.0,24.55,191.9,91.0,8.64,14.1,6,3.81,2.0,False
3332,TN,74,415,No,Yes,25,234.4,113.0,39.85,265.9,82.0,22.60,241.4,77.0,10.86,13.7,4,3.70,0.0,False

In [24]:
# Use original df to identify LA rows while preserving original indices
la_indices = df[df['State'] == 'LA'].index
la_rows = df.loc[la_indices]
la_rows.index.name = "Num Row"

# Print LA row with original row numbers
display('~' * 100, 
        '=========== All the rows for LA with original row numbers ===========', 
        '~' * 100, 
        la_rows)

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~'

'=========== All the rows for LA with original row numbers ==========='

'~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~'

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
Num Row,,,,,,,,,,,,,,,,,,,,
8,LA,117,408,No,No,0,184.5,97.0,31.37,351.6,80.0,29.89,215.8,90.0,9.71,8.7,4,2.35,1.0,False
32,LA,172,408,No,No,0,212.0,121.0,NaN,NaN,NaN,2.65,293.3,78.0,13.20,12.6,10,3.40,3.0,False
91,LA,155,415,No,No,0,203.4,100.0,34.58,190.9,104.0,16.23,196.0,119.0,8.82,8.9,4,2.40,0.0,True
148,LA,121,408,No,No,0,181.5,121.0,30.86,218.4,98.0,18.56,161.6,103.0,7.27,8.5,5,2.30,1.0,False
155,LA,151,408,No,No,0,178.7,116.0,30.38,292.1,138.0,24.83,265.9,101.0,11.97,9.8,4,2.65,0.0,False
174,LA,179,408,No,No,0,219.2,92.0,37.26,149.4,125.0,12.70,244.7,104.0,11.01,6.1,5,1.65,0.0,False
210,LA,99,415,No,No,0,241.1,72.0,40.99,155.6,98.0,13.23,188.2,109.0,8.47,11.6,10,3.13,1.0,False
215,LA,93,415,No,No,0,179.3,93.0,30.48,178.6,98.0,15.18,225.2,131.0,10.13,11.5,6,3.11,3.0,False
453,LA,149,415,No,Yes,20,198.9,77.0,33.81,274.0,88.0,23.29,190.7,76.0,8.58,14.3,9,3.86,1.0,False
534,LA,67,510,No,No,0,310.4,97.0,52.77,66.5,123.0,5.65,246.5,99.0,11.09,9.2,10,2.48,4.0,False
623,LA,172,415,No,No,0,215.7,140.0,36.67,146.3,84.0,12.44,264.6,83.0,11.91,7.1,1,1.92,3.0,False
675,LA,43,415,No,No,0,241.9,101.0,41.12,129.4,121.0,11.00,264.8,104.0,11.92,5.9,3,1.59,1.0,False
743,LA,158,408,No,No,0,202.0,126.0,34.34,163.5,86.0,13.90,195.4,84.0,8.79,10.4,6,2.81,1.0,False
748,LA,106,408,No,No,0,220.7,120.0,37.52,270.2,95.0,22.97,121.6,113.0,5.47,8.7,5,2.35,1.0,False
758,LA,108,510,No,Yes,30,276.6,99.0,47.02,220.1,113.0,18.71,177.9,95.0,8.01,9.8,6,2.65,2.0,False
778,LA,115,415,No,Yes,26,170.5,107.0,28.99,217.2,77.0,18.46,225.7,71.0,10.16,13.6,5,3.67,6.0,False
892,LA,109,415,No,Yes,27,166.9,85.0,28.37,221.2,92.0,18.80,197.3,97.0,8.88,12.3,4,3.32,1.0,True
972,LA,87,415,No,No,0,228.7,90.0,38.88,163.0,99.0,13.86,154.1,90.0,6.93,11.8,3,3.19,1.0,False
1022,LA,154,510,No,No,0,166.9,99.0,28.37,154.9,97.0,13.17,189.4,89.0,8.52,7.2,5,1.94,0.0,False
1067,LA,118,408,No,No,0,187.4,97.0,31.86,177.8,89.0,15.11,233.4,97.0,10.50,12.2,6,3.29,1.0,False
1140,LA,9,415,No,Yes,39,214.1,108.0,36.40,169.2,115.0,14.38,189.7,117.0,8.54,10.1,3,2.73,1.0,False
1203,LA,155,408,No,Yes,39,183.3,106.0,31.16,205.1,101.0,17.43,263.7,90.0,11.87,5.1,7,1.38,1.0,False
1216,LA,95,415,No,No,0,141.1,84.0,23.99,211.4,108.0,17.97,103.7,127.0,4.67,5.9,6,1.59,3.0,False
1227,LA,162,510,No,Yes,33,184.5,139.0,31.37,183.2,78.0,15.57,127.4,106.0,5.73,12.3,6,3.32,0.0,False
1305,LA,89,415,No,No,0,141.1,92.0,23.99,249.1,126.0,21.17,136.0,73.0,6.12,10.8,2,2.92,2.0,False
1351,LA,13,415,No,No,0,58.4,121.0,9.93,262.2,64.0,22.29,159.0,115.0,7.15,11.9,5,3.21,1.0,False
1415,LA,99,510,No,No,0,142.3,89.0,24.19,204.5,95.0,17.38,203.1,114.0,9.14,9.1,1,2.46,0.0,False
1446,LA,111,415,No,Yes,28,128.8,104.0,21.90,157.3,52.0,13.37,147.4,76.0,6.63,10.3,2,2.78,2.0,False
1496,LA,81,415,No,Yes,36,115.9,120.0,19.70,236.6,95.0,20.11,255.0,90.0,11.48,11.7,6,3.16,3.0,False
1779,LA,112,510,No,No,0,174.5,127.0,29.67,259.3,71.0,22.04,170.5,120.0,7.67,11.3,7,3.05,1.0,False
1948,LA,128,415,No,No,0,148.5,105.0,25.25,243.0,106.0,20.66,255.2,114.0,11.48,6.8,2,1.84,1.0,False
2055,LA,82,415,No,No,0,197.7,101.0,33.61,127.6,83.0,10.85,142.1,103.0,6.39,13.5,3,3.65,1.0,False
2112,LA,150,415,No,No,0,136.6,112.0,23.22,209.4,81.0,17.80,161.1,78.0,7.25,12.2,2,3.29,4.0,True
2197,LA,133,415,No,No,0,216.2,67.0,36.75,222.2,133.0,18.89,192.0,95.0,8.64,3.1,1,0.84,2.0,False
2324,LA,124,510,No,No,0,143.3,120.0,24.36,230.7,111.0,19.61,214.3,91.0,9.64,7.8,2,2.11,4.0,True
2341,LA,40,510,No,No,0,109.4,107.0,18.60,244.7,102.0,20.80,276.9,123.0,12.46,7.1,7,1.92,0.0,False
2346,LA,114,415,No,No,0,169.2,96.0,28.76,149.9,83.0,12.74,196.9,119.0,8.86,4.6,4,1.24,2.0,False
2458,LA,163,408,No,Yes,23,224.0,126.0,38.08,233.5,89.0,19.85,293.9,104.0,13.23,8.8,4,2.38,1.0,False
2518,LA,53,415,No,No,0,145.1,116.0,24.67,233.7,82.0,19.86,208.7,95.0,9.39,7.9,5,2.13,2.0,False
2610,LA,69,415,No,Yes,37,155.0,98.0,26.35,142.4,105.0,12.10,143.7,117.0,6.47,5.9,4,1.59,1.0,False
2722,LA,98,408,No,No,0,136.1,82.0,23.14,156.3,118.0,13.29,158.8,83.0,7.15,10.1,5,2.73,2.0,False
2804,LA,27,408,No,No,0,82.6,105.0,14.04,204.0,99.0,17.34,224.2,122.0,10.09,9.1,4,2.46,1.0,False
2875,LA,123,510,No,Yes,32,212.3,77.0,36.09,251.5,78.0,21.38,208.7,85.0,9.39,6.6,2,1.78,3.0,False
3014,LA,153,510,No,No,0,166.8,127.0,28.36,143.5,121.0,12.20,210.7,130.0,9.48,11.8,4,3.19,0.0,False
3022,LA,123,415,No,Yes,33,146.6,87.0,24.92,114.8,59.0,9.76,220.4,99.0,9.92,2.9,7,0.78,0.0,False
3060,LA,94,415,No,No,0,212.1,98.0,36.06,189.4,89.0,16.10,352.2,95.0,15.85,8.4,5,2.27,3.0,False
3138,LA,91,408,No,No,0,147.2,121.0,25.02,175.2,87.0,14.89,136.3,80.0,6.13,13.3,3,3.59,2.0,False
3145,LA,62,415,No,No,0,186.8,94.0,31.76,207.6,92.0,17.65,195.0,98.0,8.78,8.8,4,2.38,3.0,False
3178,LA,91,415,No,No,0,190.5,128.0,32.39,205.5,103.0,17.47,130.7,63.0,5.88,13.8,5,3.73,0.0,False
3302,LA,75,510,Yes,No,0,153.2,78.0,26.04,210.8,99.0,17.92,153.5,100.0,6.91,7.8,3,2.11,1.0,False
3311,LA,128,415,No,No,0,147.7,94.0,25.11,283.3,83.0,24.08,188.3,124.0,8.47,6.9,5,1.86,2.0,False

In [28]:
df = df.drop('Area code', axis=1)
display(df)

,State,Account length,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,No,Yes,25,265.1,110.0,45.07,197.4,99.0,16.78,244.7,91.0,11.01,10.0,3,2.70,1.0,False
1,OH,107,No,Yes,26,161.6,123.0,27.47,195.5,103.0,16.62,254.4,103.0,11.45,13.7,3,3.70,1.0,False
2,NJ,137,No,No,0,243.4,114.0,41.38,121.2,110.0,10.30,162.6,104.0,7.32,12.2,5,3.29,0.0,False
3,OH,84,Yes,No,0,299.4,71.0,50.90,61.9,88.0,5.26,196.9,89.0,8.86,6.6,7,1.78,2.0,False
4,OK,75,Yes,No,0,166.7,113.0,28.34,148.3,122.0,12.61,186.9,121.0,8.41,10.1,3,2.73,3.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3328,AZ,192,No,Yes,36,156.2,77.0,26.55,215.5,126.0,18.32,279.1,83.0,12.56,9.9,6,2.67,2.0,False
3329,WV,68,No,No,0,231.1,57.0,39.29,153.4,55.0,13.04,191.3,123.0,8.61,9.6,4,2.59,3.0,False
3330,RI,28,No,No,0,180.8,109.0,30.74,288.8,58.0,24.55,191.9,91.0,8.64,14.1,6,3.81,2.0,False
3331,CT,184,Yes,No,0,213.8,105.0,36.35,159.6,84.0,13.57,139.2,137.0,6.26,5.0,10,1.35,2.0,False
3332,TN,74,No,Yes,25,234.4,113.0,39.85,265.9,82.0,22.60,241.4,77.0,10.86,13.7,4,3.70,0.0,False

In [29]:
df['traveler'] = df['International plan'].apply(lambda x: 'tourist' if x == 'Yes' else 'homer')
display(df)

,State,Account length,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn,traveler
0,KS,128,No,Yes,25,265.1,110.0,45.07,197.4,99.0,16.78,244.7,91.0,11.01,10.0,3,2.70,1.0,False,homer
1,OH,107,No,Yes,26,161.6,123.0,27.47,195.5,103.0,16.62,254.4,103.0,11.45,13.7,3,3.70,1.0,False,homer
2,NJ,137,No,No,0,243.4,114.0,41.38,121.2,110.0,10.30,162.6,104.0,7.32,12.2,5,3.29,0.0,False,homer
3,OH,84,Yes,No,0,299.4,71.0,50.90,61.9,88.0,5.26,196.9,89.0,8.86,6.6,7,1.78,2.0,False,tourist
4,OK,75,Yes,No,0,166.7,113.0,28.34,148.3,122.0,12.61,186.9,121.0,8.41,10.1,3,2.73,3.0,False,tourist
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3328,AZ,192,No,Yes,36,156.2,77.0,26.55,215.5,126.0,18.32,279.1,83.0,12.56,9.9,6,2.67,2.0,False,homer
3329,WV,68,No,No,0,231.1,57.0,39.29,153.4,55.0,13.04,191.3,123.0,8.61,9.6,4,2.59,3.0,False,homer
3330,RI,28,No,No,0,180.8,109.0,30.74,288.8,58.0,24.55,191.9,91.0,8.64,14.1,6,3.81,2.0,False,homer
3331,CT,184,Yes,No,0,213.8,105.0,36.35,159.6,84.0,13.57,139.2,137.0,6.26,5.0,10,1.35,2.0,False,tourist
3332,TN,74,No,Yes,25,234.4,113.0,39.85,265.9,82.0,22.60,241.4,77.0,10.86,13.7,4,3.70,0.0,False,homer

In [34]:
def check_status_person(day, night):
    if pd.isna(day) or pd.isna(night):
        return 'unknown'
    if day > night:
        return 'day person'
    else:
        return 'night person'
df['talker_type'] = np.vectorize(check_status_person)(df['Total day minutes'], df['Total night minutes'])
display(df)

,State,Account length,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,...,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn,traveler,talker_type
0,KS,128,No,Yes,25,265.1,110.0,45.07,197.4,99.0,...,244.7,91.0,11.01,10.0,3,2.70,1.0,False,homer,day person
1,OH,107,No,Yes,26,161.6,123.0,27.47,195.5,103.0,...,254.4,103.0,11.45,13.7,3,3.70,1.0,False,homer,night person
2,NJ,137,No,No,0,243.4,114.0,41.38,121.2,110.0,...,162.6,104.0,7.32,12.2,5,3.29,0.0,False,homer,day person
3,OH,84,Yes,No,0,299.4,71.0,50.90,61.9,88.0,...,196.9,89.0,8.86,6.6,7,1.78,2.0,False,tourist,day person
4,OK,75,Yes,No,0,166.7,113.0,28.34,148.3,122.0,...,186.9,121.0,8.41,10.1,3,2.73,3.0,False,tourist,night person
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3328,AZ,192,No,Yes,36,156.2,77.0,26.55,215.5,126.0,...,279.1,83.0,12.56,9.9,6,2.67,2.0,False,homer,night person
3329,WV,68,No,No,0,231.1,57.0,39.29,153.4,55.0,...,191.3,123.0,8.61,9.6,4,2.59,3.0,False,homer,day person
3330,RI,28,No,No,0,180.8,109.0,30.74,288.8,58.0,...,191.9,91.0,8.64,14.1,6,3.81,2.0,False,homer,night person
3331,CT,184,Yes,No,0,213.8,105.0,36.35,159.6,84.0,...,139.2,137.0,6.26,5.0,10,1.35,2.0,False,tourist,day person
3332,TN,74,No,Yes,25,234.4,113.0,39.85,265.9,82.0,...,241.4,77.0,10.86,13.7,4,3.70,0.0,False,homer,night person